# Generated by Django 4.2.1 on 2023-05-29 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_clinica', '0002_alter_paciente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('especialidad', models.CharField(choices=[('medicina general', 'Medicina general'), ('cardiologia', 'Cardiologia'), ('pediatria', 'Pediatria'), ('dermatologia', 'Dermatologia'), ('gastroenterologia', 'Gastroenterologia'), ('ginecologia', 'Ginecologia'), ('neumologia', 'Neumologia'), ('psiquiatria', 'Psiquiatria'), ('oncologia', 'Oncologia'), ('otro', 'Otro')], default='medicina general', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cita', models.DateField()),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
